spring.application.name=payment-order-service

spring.datasource.url=jdbc:postgresql://localhost:5433/payment_orders
spring.datasource.username=payment_user
spring.datasource.password=payment_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Wait for db to be up before failing
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
