spring.application.name=payment-order-service

spring.datasource.url=jdbc:postgresql://localhost:5433/payment_orders
spring.datasource.username=payment_user
spring.datasource.password=payment_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Wait for db to be up before failing
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

# disable osiv -> ideally this should throw error as we are deserializing and getting data
# in some end points like get order as it is getting line items of the order in 
# deserialization part only. lets check. if lazy initialization error comes, lets make this true and test
# in a ideal scenario, this should be false only
spring.jpa.open-in-view=false

mock-vendor.url=http://localhost:8081
